const blogs={
    "Why-it-is-a-good-investment-to-have-a-keyless-fingerprint-door-lock":{
        title:"Why it is a good investment to have a keyless fingerprint door lock",
        img:"../../public/assets/new_assets/images/blog3.jpg",
        desc:"The new technology that makes up a digital lock for the house is the new digital keyless door locks that can help to make a home or office more secure. This type of door lock is not just a feature that will help to keep people from being able to get into the home..With the use of keyless door locks, a person will be able to use a wireless sensor that is able to sense when a person tries to open a door or window. This is an important feature for any home or office as it can help to ensure that a door or window will not be opened without someone being able to open it. If someone were able to open a door or window without getting a signal from the sensor, they would have the ability to enter the home or office and could potentially cause damage to the property.",
    },
    "Everything-you-need-to-know-about-digital-fingerprint-locks":{
        title:"Everything you need to know about digital fingerprint locks",
        img:"../../public/assets/new_assets/images/blog2.jpg",
        desc:"In the present times, securing yourself and your loved ones by whatever means necessary has become of crucial importance..With the increasing crime stats in every state of the country, you can never be too certain of what you may or may not have to face in the unforeseen future and its circumstances In such a case, it becomes of prime importance to find a lock system that is secure enough to provide you a relieved good night’s sleep without worrying about what it might mean to rest peacefully. With the use of keyless door locks, a person will be able to use a wireless sensor that is able to sense when a person tries to open a door or window. This is an important feature for any home or office as it can help to ensure that a door or window will not be opened without someone being able to open it. If someone were able to open a door or window without getting a signal from the sensor, they would have the ability to enter the home or office and could potentially cause damage to the property. ",
    },
    "Tips-to-help-you-buy-the-best-digital-gate-lock":{
        title:"Tips to help you buy the best digital gate lock",
        img:"../../public/assets/new_assets/images/blog4.jpg",
        desc:"Digital gates came into existence to replace traditional key locks, and as such have proved to be very useful. However, you have to realize that there are a plethora of different digital gates in the marketplace, from which you must choose the right one for your workplace or home. The first thing that, you need to look for when comparing digital gates is their locking mechanisms. You may also want to check out the features of various models. The locking mechanisms that different companies offer can differ considerably, which means that one model may be better than another when it comes to locking. You also need to ensure that the locking mechanism is easy to use.",
    },
    "Smart-door-locks-for-Glassdoor":{
        title:"Smart door locks for Glassdoor",
        img:"../../public/assets/new_assets/images/blog1.jpg",
        desc:"There is a myriad of benefits that come with smart locks. These include keyless entry, security cameras, and more. However, the most important benefit is that smart locks allow you full control over who can enter your home. As a homeowner, this means you no longer need to worry about whether or not your guests will remember their keys when they leave! Our blog post on the best smart locks for sliding glass doors has all the information about how to transform your sliding glass door into an easy-going entrance with low maintenance and a high level of convenience.",
        desc1:"Smart☺ locks are the new way to go. While they can be hackable, they're still incredibly useful in preventing unwanted intrusions into your home.",
        desc2:"For those who don't want to read all the details, here is our list of the top three best smart locks for sliding glass doors.",
        desc3:"Lavna Locks-  Connect Wi-Fi Enabled Touchscreen Deadbolt with Keyless eKey. Works with Alexa and Google Assistant. Auto Unlock and Auto-Lock This lock is compatible with both Android and iOS devices so you can easily access it through your mobile device. It also has an auto-lock feature that will automatically lock your door after a set period if you don’t specifically tell it to stay unlocked. It also has a two-generation upgrade on its two-factor authentication system, which allows you to use your smartphone or tablet as the key.",
        desc4:"This lock comes with a free smartphone app that allows you to control your home lock and will even allow you to change the lock’s settings remotely through your phone. Keyless entry works via Bluetooth and a free key fob can be purchased separately if you don’t want to deal with a bunch of manual keys.",
        desc5:"This lock offers full compatibility with other Lavna Smart Locks and also features Wi-Fi connectivity so it can communicate with smart home systems such as Amazon Alexa, Google Home, Nest Thermostat, and Wink Hub.",
        desc6:"Aeon Command Lock Bluetooth Smart Deadbolt Alarm Keypad :-",
        desc7:"Works with Alexa and Google Home. Fully IP67 Waterproof.This lock features a touch screen that is easy to use and has motion sensors, which will automatically lock if it has been opened or closed by a person without the correct key. It also has an alarm system that will activate if someone tries to break into the door using a tool like a pry bar or bolt cutter.",
        desc8:"The lock itself looks sleek as it is made of brushed metal and can either be wall-mounted or used on the door instead of using screws.",
        desc9:"The Lockey 2500: is an add-on to your sliding door and enables keyless entry. It does only enable one key pin, so you will have to stake that around with your family and friends who will be using the lock. This too comes with two keys for unlocking and as well as locking. Yeah, we know, keys are old-fashioned but keeping that extra accessibility is nice."
    },
    "What all you need to know before investing smart door lock":{
        title:"What all you need to know before investing smart door lock",
        img:"../../public/assets/new_assets/img2/blog5.jpg",
        desc:"“Survival of the fittest”- only those who are able to adapt themselves to the changing environment are able to survive in this world. With constant updates and improvement, we as human beings are also getting dependent on technology. The Internet has changed the way we used to work. Our houses are filled with modern gadgets and the latest addition to this series is smart door locks.",
        desc1:"With the changing times, Ensuring privacy and safety of our home and our close ones is an important issue. Surveillance cameras, Smart door locks are tangible ways that solve the majority of the security concerns of people and bring them peace of mind.",
        desc2:"However, while people seem to be too interested in the idea of buying a smart lock system of their house, they are also not sure which smart lock will work for them.",
        desc3:"Here are few things that you should consider while investing in a smart lock - ",
        desc4:"1. Compatibility",
        desc5:"First thing that you should check is whether your door is compatible with smart door locks or not. There are different kinds of smart door lock options available in the market that come with different options. Check which one is perfect for your door. Apart from that you also need to see that your door is thick enough to support the smart lock system. Understanding this, Lavna has created such smart locks that are compatible with every type of door- whether metallic or wooden. It supports every structure and fits with them.",
        desc6:"2. Options and features",
        desc7:"After finding the perfect lock for your door, the next thing you should check is the features that company offers with their locks- Whether you want to go with Wi-Fi enabled locks or Bluetooth one, with or without voice command? Does your lock support add-ons and upgrade over the internet? ",
        desc8:"3. Convenience ",
        desc9:"Apart from security, convenience is another thing why people want to invest in a smart door lock. While most of the door locks come with hassle free installation options, there are also some that require heavy tools. You can avoid investing in them. You can always ask for a demo to understand the working of smart lock and see all features you are comfortable with. You can see what all options are available to lock, unlock and open the door from both inside and outside.",
        desc10:"4. Battery life",
        desc11:"You really don’t want to spend your time changing batteries after every few weeks. You should prefer locks with easily accessible compartments and longer battery life. Also, it is always advisable to keep a spare battery with you to avoid any emergency situation. Smart locks have added a new convenience to life. While traditional locks also do the work, they do not seem to be efficient in these changing times that demands just more than security.",
        desc12:"Lavna with their wide range of smart door locks offers a complete security solution to your home and other areas. With added advanced features, our locks not only upgrade your security but also makes your life convenient."
    },
    "Reasons you need to switch to smart door locks today":{
        title:"Reasons you need to switch to smart door locks today",
        img:"../../public/assets/new_assets/img2/blog6.jpg",
        desc:"Technology has never failed to amaze us. It strikes you right there when you least expect it. With the dynamics of technology changing every second,  we often miss appreciating several updates that have truly reinvented the way we used to perform. One of those is our security system. ",
        desc1:"Earlier, having accessible smart security devices was nothing less than owning a luxury but Lavna takes pride in producing a highly durable, trustable, and affordable series of smart door lock systems- an all-in-one system with a contemporary design for your overall security.",
        desc2:"Strangely enough, smart door locks are one of the best results of automation improvement. They not only add a style element but also makes your life utterly comfortable as they are equipped with the latest technological updates. With all shapes and sizes to suit every need, the demand for smart locks has grown tremendously in the past few years.",
        desc3:"If you are among the few who haven’t switched to Smart door locks, here are the reasons why you should do it now!",
        desc4:"Key-free :-",
        desc5:"With smart locks to your rescue, you never have to worry about losing your keys again.  The main purpose of these smart locks is to provide you comfort and convenience. Lavna locks come with different features including smart access through google assistant/Alexa, fingerprint sensor, OTP recognition, and other personalized control features. Installed with WiFi, it allows you to lock doors from anywhere. ",
        desc6:"Apart from that, if you feel that you are not a password person who can remember another pin to open the door, don't worry. OTP system and fingerprint sensors unlock your door without any worries.",
        desc7:"Track entries and exits",
        desc9:"The changing times don’t reflect a lifestyle where you allow any stranger. Smart locks help you track who entered and exited the house. You can assign pins to your family members and avoid any unwanted entry.  With WiFi systems, you can receive an alert on your smartphone as soon as someone will try to enter your house.",
        desc10:"Stylish :-",
        desc11:"Up your front door game with a lock system that not only guarantees the security of your home but also spruces up the look of your front door lock with its sleek and contemporary designs. Earlier the major concern for people regarding the smart locks was their bulky and heavy designs. However, Lavna smart door locks come with a modern design and that will fit on both wooden or metal doors.",
        desc12:"Security concerns :-",
        desc13:"Connected with smart networks, Lavna locks make sure you are notified every time enters your home.  With smart door locks, there is no need to duplicate keys and risks the security of your home. You can set entry and exit time using a secured passcode, eliminating the risk. ",
        desc14:"Easy to use and affordable :-",
        desc15:"Equipped with the latest updates, it is often considered that smart locks are highly expensive. Lavna locks bring you an array of fully updated and classic lock designs that fits everyone’s budget.",
        desc16:"Who knew all you needed was a smart door lock as a solution to all your home security concerns. With our detailed guide, you can find the best suit for your needs. Upgrade your security system with a responsible choice with us."
    },
    "The Best Smart Door Locks In India 2021":{
        title:"The Best Smart Door Locks In India 2021",
        img:"../../public/assets/new_assets/img2/blog7.jpg",
        desc:"One of the most recent trends in home security is smart locks. Smart locks have the ability to automatically unlock doors when you approach, or lock up if someone walks by while you're away. This way, your lock can be tailored to fit your lifestyle and needs without sacrificing safety. And because smart locks are so popular, there are a plethora of options out there to choose from. In this article, we're going to go over some of the best smart locks on the market today. We'll be looking at the features that each lock offers, as well as a few drawbacks. ",
        desc1:"The Big Benefits of a Smart Door Lock System",
        desc2:"There are lots of benefits that come with installing a smart door lock system. It can stop someone from opening the door without your permission. It can control who has access to your home so you don’t have to worry about people you don’t trust coming in. The installation is quick and easy, and it can even be done by yourself if you want to save money on an installation fee. A smart door lock system is the best way to protect yourself, your loved ones, or your property from thieves or unwanted visitors by giving them limited access through codes.",
        desc3:"Benefits of installing a digital smart lock",
        desc4:"Here is a list of big benefits that come with installing a great smart door lock system :-",
        desc5:"1. High-end Security – If you want to protect yourself and your home from unwanted intruders, then you need to install a smart door lock. They can’t access your home without the proper codes. If they do somehow get the code, it will be deactivated and no longer available immediately after they leave. You can also send temporary codes and revoke them as quickly as possible if needed.",
        desc6:"2. Reduce Cost – Smart door locks can help reduce your energy costs by unlocking doors when someone enters or exiting instead of leaving them open.",
        desc9:"3. Save Time – Smart door locks have a variety of features that can save you time. For example, if your hands are full with grocery bags on the way home from the store, you can open the door with your phone on your way home without dropping anything.",
        desc10:"4. Increase Security – This is a dual benefit that will protect both you and your property from being stolen or damaged by intruders. You can easily program codes to family members for easy access, but they won’t be able to let anyone else in without your permission.",
        desc11:"5. Let in a few friends – It can be fun to have company come over for a while, but you don’t want to leave the door open so anyone walking by can get in. With a smart door lock system, only the person inside the house will be able to get in using specific codes that they can create themselves or by setting up temporary codes.",
        desc12:"6. Create access lists – Building access lists is very easy with a smart door lock system, and you should do it from time to time. Assigning family members or other trusted people a keypad code is also an option if you want your whole family or your guests to have access without having everyone’s door codes on file.",
        desc13:"The best smart locks in 2021",
        desc14:"Today we're highlighting the best smart locks of 2021. These will all be on Amazon and can easily be found. Check out the article for some great suggestions!",
        desc15:"The below quoted list gives a quick introduction to what a smart lock is and why it makes sense to buy one and then lists the latest brands that are available today.",
        desc16:"1. Schlage Connect Touchscreen Deadbolt ",
        desc17:"​Schlage is one of the most popular brands of locks along with Kwikset and Yale. Schlage makes an excellent smart lock as well. Schlage's product is a great option if you have a newer or high-quality door knob already installed . All you need to do is remove the deadbolt from your door and replace it with Schlage's smart lock. The lock is also easy to install yourself, if you're feeling brave. Like the August Smart Lock, Schlage's product can be unlocked using your smartphone or Bluetooth-enabled device.",
        desc18:"Pros: One of the best security options on the market • Excellent value • Easy installation Cons: Doesn't work with all door knobs • Requires a 9V battery.",
        desc19:"This smart lock uses Bluetooth to connect your phone with the door's lock. The touchscreen display allows you to easily access your settings, programming, and more.The app also gives you information on who has entered or exited the home. You can set up temporary codes for guests or cleaning personnel, if selected.",
        desc20:"2. SmartCode 916 Touchscreen Deadbolt",
        desc21 :"​This lock features an Auto-Lock feature that allows you to send it back on the front door handle. The Auto-Lock uses a 9-volt battery, ensuring that you only have to replace the battery every two years.This lock also has customizable entry codes, allowing you to have different codes for different people or even for certain days of the week.",
        desc22:"3. Lavna Smart Lock",
        desc23:"The Lavna Smart Lock is the best option if you want a combination of smart technology and security. For starters, it can be used with a Bluetooth-enabled device or your smartphone. After you've installed the app on your phone, simply tap 'unlock' on the screen to open it up with ease. If you'd rather, you can also use a key to open the lock. The Lavna has a sleek, modern design and comes in six different colors. It is compatible with both single and double cylinder deadbolts. Lavna is one of the most popular smart locks because it is relatively cheap compared to other brands, but also very reliable. The lock allows you to monitor who enters and exits the home through your phone app or web portal.",
        desc24:"This lock uses Bluetooth to connect with your phone, making it easier for you to control the lock anywhere in range.",
        desc25:"Pros: Great security features • Easy installation • Mobile app is easy to use • Good value for price.",
        desc26:"4. Goji Smart Lock Pro",
        desc27:"​The Goji Smart Lock allows you to instantly unlock your door using your phone's fingerprint scanner. Your fingerprint doubles as a combination code, allowing you to immediately enter the home without entering a regular combination code first.",
        desc28:"5. Daisy WiFi Enabled Video Doorbell",
        desc29:"One of the most important things to consider when installing a smart lock is safety. The Daisy Wifi Enabled Video Doorbell is a great option if you want something that will alert you not only when someone approaches, but also when they actually arrive at your door."
    },
    "Common myths about smart door locks":{
        title:"Common myths about smart door locks",
        img:"../../public/assets/new_assets/img2/blog8.jpg",
        desc:"Locks are an inseparable part of our day to day lives. With everything upgrading itself with the changing time, technology has brought changes in the way lock functions.",
        desc1:"However, handling different keys is no less than a tedious task. But with the advent of smart locks, people adopted the key-less lifestyle and got the liberty to move in and out freely, without worrying.",
        desc2:"The simplification digital locks offered were tremendous and the product started ruling the market. There is no denying in the fact that it has become a basic necessity in a modern household.  They provide some truly extra features that puts a strong point forward  why everyone should get a smart lock for their home. Restricted entry, alarms, and remote access are few such features that makes smart door locks more secure than the traditional ones.",
        desc3:"However, there are still concerns that are keeping people away from embracing this product. ",
        desc4:"We have listed down some common misconceptions and myths about smart locks that you can ignore",
        desc5:"1. Smart locks are technical",
        desc6:"When it comes to smart door locks, people often mistake that they will involve a comprehensive technical process and they will have to spend a lot of time while lock or unlocking their home. However, smart locks are designed to simplify the process and not complicate it. With an easy procedure, you can learn to operate them without any complication. ",
        desc9:"2. Difficult Installation ",
        desc10:"Another one of the myths attached to smart locks is they will require a lot of wiring and have a difficult installation process while to install a smart lock, all you need is a screwdriver.",
        desc11:"They do not involve any wiring and rather work on batteries. Installing them is as easy as installing a cabinet lock. Once installation is complete, download the app and set the preferences and you are all set to use them.",
        desc12:"3. They are easy to hack ",
        desc13:"People think that their smart lock can be hacked easily by tracing their details however, it is necessary to understand that every smart lock comes with an encryption code. Encryption is a process of converting data into a secret code which cannot be accessed by all.",
        desc14:"4. They are bulky",
        desc15:"You don’t have to compromise with your style element. Smart door locks not only come with effective security options but their sleek design and minimalist approach will make you fall in love with them. ",
        desc16:"5. What if the power goes out? ",
        desc17:"Smart locks do not require any wiring and operate on batteries, meaning your lock will still be functional in case there is no power. The app linked with the lock will send timely notification to the person when they need to be changed. So even if there’s no power, you don’t have to worry. ",
        desc18:"In these times, we want everything to be secured at best. While the traditional lock and security system were able in keeping people out but with changing times just that is not enough. Investing in a good smart lock can open up new possibilities for you, giving your security system a much-required edge. ",
        desc19:"Lavna is always here to clear all your security concerns with their latest and updated security solution. With our smart door locks that are compatible with every door, you don’t have to compromise your security for convenience. ",
    },
    "Why Hospitals should adopt smart digital locks":{
        title:"Why Hospitals should adopt smart digital locks?",
        img:"../../public/assets/new_assets/img2/blog9.jpg",
        desc:"Coronavirus is one such kind of deadly disease that has taken a toll on not just one part but the entire globe. With thousands of death every day, several people lost their close ones to this disease.",
        desc1:"The countries were sent into lockdown for months to mitigate the spread of the virus however, hospitals were the place that faced the major challenge. There was a constant movement of sick hospitalized patients carrying an infectious disease, making doctors, nurses, and other frontlines workers even more vulnerable to the disease.",
        desc2:"While several precautions were taken care to avoid direct contact with the contaminated surfaces, it became extremely difficult, despite several sanitizations, to avoid repeated contact of healthcare workers with these surfaces. ",
        desc3:"In these tough times, new technology into their healthcare system can improve security and lower infection rate by a significant level ",
        desc4:"Here are a few ways that smarter cabinet and locking mechanisms can help medical teams reduce the risk of hospital-acquired infections-",
        desc5:"Reduce multi-person contact surface",
        desc6:"Traditional locks involve a lot of physical components and this exposure can lead to the unnecessary transfer of the virus. With Lavna digital locks, medical staff no longer need to handle and manage key as digital locks can be accessed through several ways including WiFi, Bluetooth, and voice command.",
        desc9:"Get the digital access",
        desc10:" In traditional locks, more keys can increase the risk of unauthorized access. With several physical keys, there is also the risk of getting misplaced but in the current time when there is constant movement, limiting the number of access is not the available option. This is when smart locks can be really helpful. Generating separate code for digital access can be implemented for better functionality.",
        desc11:"Better security",
        desc12:"Amid the pandemic, there was more panic and hesitancy among people around the world and there were several cases where we saw people breaking the security system to get out of the hospital because of the fear the disease created.",
        desc13:"Electronic locks can be installed at different entry points to upgrade the security options. Hospitals can also decide to give specialized access to different departments to avoid any unwanted entry and exit in the premises. ",
        desc14:"Fewer components to clean",
        desc15:"This is a friendly reminder that traditional locks also get dirty and carry a lot of germs. By switching to digital locks you will reduce the constant touch to the main lock and will thus reduce the possibility of virus transfer. E-lock solutions are not exposed to direct contacts which further reduces the need for constant disinfection of keys, locks, and door handles. These devices can be easily cleaned and sanitize with just a wipe.",
        desc16:"Smart locks cannot be a replacement for existing practices but they can act as a supplement. Take the next step in reducing hospital-acquired infections with smart locks from Lavna. Our professional staff will help you to get one of the best smart locks without compromising on convenience and security. ",
    }
}

module.exports = blogs;